SilverStripe\Core\Manifest\ModuleManifest:
  project: mysite
SilverStripe\View\SSViewer:
  theme: calendar
SilverStripe\Dev\Debug:
  friendly_error_httpcode: true
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - EventFindaExtension
    - HappSiteConfig
SilverStripe\Core\Injector\Injector:
  SilverStripe\Forms\HTMLEditor\TinyMCEScriptGenerator: 'SilverStripe\Forms\HTMLEditor\TinyMCEGZIPGenerator'
