---
Name: calendarsiteroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'pagefunction//$Action/$ID'  : 'Page_Controller'
    'calendarfunction//$Action/$ID'  : 'CalendarPage_Controller'